method: 'random'
metric: 
  name: 'acc'
  goal: 'maximize'   
parameters: 
  batch_size:
    values: [256, 128, 64, 32]
  input_channel: 
    values: [32, 16, 8, 4, 1]
  num_channels:
    values: [[100, 100], [100], [100, 100, 100]]
