device: "cuda:0"
model : "vgg"
head: "tcn"

input_channel: 8
input_size: 8
output_size: 11
num_channels: [500, 100]

epochs: 30
save_folder: "./weight/"
batch_size: 256
shuffle: False
n_sample: 1

lr : 0.001
type: "feat"

loss_type: "ce"
# pairs: []
pairs: [["moving","hidden"], ["painting","battle"]]

repeat: 50

# wandb: True
wandb: False
