device: "cuda:0"
model : "vgg"
head: "NN"

input_channel: 512
align_size: 8

epochs : 30
save_folder : "./weight/"
batch_size: 256
shuffle: True
n_sample: 1

lr : 0.001
type : "feat"

loss_type: "ce"
pairs: []

repeat: 50

wandb: True
