device: "cuda:0"
model : "vgg"
head: "tcn"

input_channel: 16
input_size: 8
output_size: 11
num_channels: [200, 100]

epochs: 30
save_folder: "./weight/"
batch_size: 128
shuffle: False
n_sample: 1

lr : 0.001
type: "feat"

repeat: 50
